from __future__ import annotations

import json
import shutil
from pathlib import Path


ROLE_MODELS = {
    "architect": "opus",
    "planner": "opus",
    "developer": "sonnet",
    "reviewer": "opus",
    "qa": "sonnet",
    "publisher": "haiku",
}

AGENT_INSTRUCTIONS = """# Agent Instructions

Read `agentkit.toml` or `.agent/project.toml` before acting. Treat `core/` as the canonical source
of workflow and security policy. Require human approval where the manifest or core policy requires
it; never self-approve, force-push, merge, release, retrieve credentials, or print secrets.

Keep governed artifacts under `docs/agent/` with TOML frontmatter. Preserve unrelated changes and
run `agentkit validate` plus the configured project checks before reporting completion.
"""


def package_root() -> Path:
    checkout_root = Path(__file__).resolve().parents[2]
    if (checkout_root / "core").is_dir():
        return checkout_root
    resources = Path(__file__).resolve().parent / "resources"
    if (resources / "core").is_dir():
        return resources
    raise FileNotFoundError("Governed Agent SDLC scaffold resources are missing")


def generate_claude(root: Path, *, force: bool = False) -> list[Path]:
    claude = root / ".claude"
    agents = claude / "agents"
    agents.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []

    for role, model in ROLE_MODELS.items():
        path = agents / f"{role}.md"
        if path.exists() and not force:
            continue
        tools = "Read, Glob, Grep, Bash, Write, Edit"
        body = f'''---
name: {role}
description: Governed {role} role generated by Governed Agent SDLC. Invoke explicitly.
model: {model}
tools: {tools}
---

Read `AGENTS.md`, then read whichever of `agentkit.toml` or `.agent/project.toml` exists, and read
`core/roles/{role}.toml` before acting.
Stay within the role's declared authority and produce the required artifact evidence.
'''
        path.write_text(body, encoding="utf-8")
        generated.append(path)

    settings_path = claude / "settings.json"
    if force or not settings_path.exists():
        settings = {
            "permissions": {
                "deny": ["Read(**/.env)", "Read(**/.env.*)", "Read(**/*credential*)"]
            },
            "hooks": {
                "PreToolUse": [
                    {
                        "matcher": "Bash|Read|Glob|Grep",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_credentials.py",
                                "timeout": 10,
                            }
                        ],
                    },
                    {
                        "matcher": "Bash",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_git.py",
                                "timeout": 10,
                            }
                        ],
                    },
                    {
                        "matcher": "Write|Edit",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_role_scope.py",
                                "timeout": 10,
                            }
                        ],
                    },
                ]
            },
        }
        settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
        generated.append(settings_path)
    return generated


def install_scaffold(destination: Path, *, name: str) -> list[Path]:
    source = package_root()
    copied: list[Path] = []
    for relative in ("core", "hooks", "profiles"):
        src = source / relative
        dst = destination / relative
        if not dst.exists():
            shutil.copytree(src, dst)
            copied.append(dst)
    manifest = destination / ".agent" / "project.toml"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    if not manifest.exists():
        manifest.write_text(
            f'''version = 1
protected_areas = [
  "authentication",
  "authorization",
  "database-schema",
  "billing",
]

[project]
name = "{_toml_escape(name)}"
topology = "monorepo"

[[repositories]]
id = "root"
path = "."
profiles = ["generic"]

[workflow]
require_spec = true
require_plan = true
require_review = true
require_qa = true
''',
            encoding="utf-8",
        )
        copied.append(manifest)
    instructions = destination / "AGENTS.md"
    if not instructions.exists():
        instructions.write_text(AGENT_INSTRUCTIONS, encoding="utf-8", newline="\n")
        copied.append(instructions)
    return copied


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")
