from __future__ import annotations

import json
import shutil
from pathlib import Path

ROLE_MODELS = {
    "architect": "opus",
    "planner": "opus",
    "developer": "sonnet",
    "reviewer": "opus",
    "qa": "sonnet",
    "publisher": "haiku",
}

ROLE_DESCRIPTIONS = {
    "architect": "Define approved specifications and system boundaries.",
    "planner": "Turn approved specifications into scoped task graphs.",
    "developer": "Implement only approved task scope and verification.",
    "reviewer": "Independently review changes without repairing source.",
    "qa": "Verify acceptance criteria and record reproducible evidence.",
    "publisher": "Publish only after review, QA, and human approval.",
}

AGENT_INSTRUCTIONS = """# Agent Instructions

Read `agentkit.toml` or `.agent/project.toml` before acting. Treat `core/` as the canonical source
of workflow and security policy. Require human approval where the manifest or core policy requires
it; never self-approve, force-push, merge, release, retrieve credentials, or print secrets.

Keep governed artifacts under `docs/agent/` with TOML frontmatter. Preserve unrelated changes and
run `agentkit validate` plus the configured project checks before reporting completion.
"""


def package_root() -> Path:
    checkout_root = Path(__file__).resolve().parents[2]
    if (checkout_root / "core").is_dir():
        return checkout_root
    resources = Path(__file__).resolve().parent / "resources"
    if (resources / "core").is_dir():
        return resources
    raise FileNotFoundError("Governed Agent SDLC scaffold resources are missing")


def generate_claude(root: Path, *, force: bool = False, dry_run: bool = False) -> list[Path]:
    claude = root / ".claude"
    agents = claude / "agents"
    generated: list[Path] = []

    for role, model in ROLE_MODELS.items():
        path = agents / f"{role}.md"
        if path.exists() and not force:
            continue
        tools = "Read, Glob, Grep, Bash, Write, Edit"
        body = f"""---
name: {role}
description: Governed {role} role generated by Governed Agent SDLC. Invoke explicitly.
model: {model}
tools: {tools}
---

Read `AGENTS.md`, then read whichever of `agentkit.toml` or `.agent/project.toml` exists, and read
`core/roles/{role}.toml` before acting.
Stay within the role's declared authority and produce the required artifact evidence.
"""
        if _write_text(path, body, force=force, dry_run=dry_run):
            generated.append(path)

    settings_path = claude / "settings.json"
    if force or not settings_path.exists():
        settings = {
            "permissions": {"deny": ["Read(**/.env)", "Read(**/.env.*)", "Read(**/*credential*)"]},
            "hooks": {
                "PreToolUse": [
                    {
                        "matcher": "Bash|Read|Glob|Grep",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_credentials.py",
                                "timeout": 10,
                            }
                        ],
                    },
                    {
                        "matcher": "Bash",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_git.py",
                                "timeout": 10,
                            }
                        ],
                    },
                    {
                        "matcher": "Write|Edit",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "uv run --no-project python hooks/guard_role_scope.py",
                                "timeout": 10,
                            }
                        ],
                    },
                ]
            },
        }
        if not dry_run:
            settings_path.parent.mkdir(parents=True, exist_ok=True)
            settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
        generated.append(settings_path)
    return generated


def generate_codex(root: Path, *, force: bool = False, dry_run: bool = False) -> list[Path]:
    """Generate additive project-scoped Codex configuration.

    Codex discovers the repository's existing AGENTS.md natively. The generated config only
    declares role-specific instruction layers and additive guard hooks; it never edits user-level
    trust, authentication, provider, model, telemetry, approval, or sandbox configuration.
    """

    codex = root / ".codex"
    generated: list[Path] = []
    role_blocks: list[str] = []
    read_only_roles = {"architect", "planner", "reviewer", "qa", "publisher"}
    for role, description in ROLE_DESCRIPTIONS.items():
        role_path = codex / "agents" / f"{role}.toml"
        role_prefix = 'sandbox_mode = "read-only"\n\n' if role in read_only_roles else ""
        role_body = role_prefix + (
            'developer_instructions = """\n'
            "Read AGENTS.md, the active project manifest, and "
            f"core/roles/{role}.toml before acting.\n"
            f"Operate only as the governed {role} role. "
            "Never self-approve, retrieve credentials, bypass protected branches, merge, or "
            "release without the required human decision.\n"
            '"""\n'
        )
        if _write_text(role_path, role_body, force=force, dry_run=dry_run):
            generated.append(role_path)
        role_blocks.extend(
            [
                "",
                f"[agents.{role}]",
                f'description = "{description}"',
                f'config_file = "agents/{role}.toml"',
            ]
        )

    hook_path = codex / "hooks" / "pre_tool_use.py"
    hook_source = Path(__file__).with_name("codex_hook.py").read_text(encoding="utf-8")
    if _write_text(hook_path, hook_source, force=force, dry_run=dry_run):
        generated.append(hook_path)

    hooks_path = codex / "hooks.json"
    hook_command = (
        'uv run --no-project python "$(git rev-parse --show-toplevel)/.codex/hooks/pre_tool_use.py"'
    )
    hook_command_windows = hook_command
    hooks = {
        "description": "Governed Agent SDLC credential and git safety guardrails.",
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "*",
                    "hooks": [
                        {
                            "type": "command",
                            "command": hook_command,
                            "commandWindows": hook_command_windows,
                            "timeout": 10,
                            "statusMessage": "Checking governed safety policy",
                        }
                    ],
                }
            ]
        },
    }
    if _write_text(
        hooks_path,
        json.dumps(hooks, indent=2) + "\n",
        force=force,
        dry_run=dry_run,
    ):
        generated.append(hooks_path)

    config = "\n".join(
        [
            'project_root_markers = [".git", "agentkit.toml", ".agent"]',
            "",
            "[features]",
            "multi_agent = true",
            "hooks = true",
            *role_blocks,
            "",
        ]
    )
    config_path = codex / "config.toml"
    if _write_text(config_path, config, force=force, dry_run=dry_run):
        generated.append(config_path)
    return generated


def install_scaffold(destination: Path, *, name: str, dry_run: bool = False) -> list[Path]:
    source = package_root()
    copied: list[Path] = []
    for relative in ("core", "hooks", "profiles"):
        src = source / relative
        dst = destination / relative
        if not dst.exists():
            if not dry_run:
                shutil.copytree(src, dst)
            copied.append(dst)
    manifest = destination / ".agent" / "project.toml"
    if not manifest.exists():
        body = f'''version = 1
protected_areas = [
  "authentication",
  "authorization",
  "database-schema",
  "billing",
]

[project]
name = "{_toml_escape(name)}"
topology = "monorepo"

[[repositories]]
id = "root"
path = "."
profiles = ["generic"]

[workflow]
require_spec = true
require_plan = true
require_review = true
require_qa = true
'''
        if not dry_run:
            manifest.parent.mkdir(parents=True, exist_ok=True)
            manifest.write_text(body, encoding="utf-8")
        copied.append(manifest)
    instructions = destination / "AGENTS.md"
    if not instructions.exists():
        if not dry_run:
            instructions.parent.mkdir(parents=True, exist_ok=True)
            instructions.write_text(AGENT_INSTRUCTIONS, encoding="utf-8", newline="\n")
        copied.append(instructions)
    return copied


def _write_text(path: Path, body: str, *, force: bool, dry_run: bool) -> bool:
    if path.exists() and not force:
        return False
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8", newline="\n")
    return True


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")
